"""Deterministic mock chat model.

The platform must run end to end with zero API keys (spec §19). This model
never calls out to the network. Its trick for producing *useful* structured
output without an LLM: prompts in this codebase always embed the frozen
evidence dict as literal JSON using the exact field names of the target
Pydantic output model (see app/agents/structured.py), so the mock can extract
real numbers/enums straight out of its own input text instead of inventing
them - which is also, not coincidentally, what a well-behaved real LLM should
do when told "do not alter these values".

For any field it cannot find verbatim in the prompt, it deterministically
synthesizes a value seeded from a SHA-256 hash of the prompt text, so the same
prompt always yields the same mock response.
"""

from __future__ import annotations

import hashlib
import json
import random
import re
from typing import Any, Optional, Union, get_args, get_origin

from langchain_core.callbacks import AsyncCallbackManagerForLLMRun, CallbackManagerForLLMRun
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.outputs import ChatGeneration, ChatResult
from pydantic import BaseModel


def _seed_from_text(text: str) -> int:
    return int(hashlib.sha256(text.encode("utf-8")).hexdigest()[:12], 16)


_JSON_VALUE_RE_TEMPLATE = r'"{key}"\s*:\s*("(?:[^"\\]|\\.)*"|-?\d+(?:\.\d+)?|true|false|null)'


def _extract_from_text(text: str, key: str) -> Any:
    pattern = _JSON_VALUE_RE_TEMPLATE.format(key=re.escape(key))
    match = re.search(pattern, text)
    if not match:
        return None
    raw = match.group(1)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return raw.strip('"')


def _unwrap_optional(annotation):
    origin = get_origin(annotation)
    if origin is Union:
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return args[0], get_origin(args[0]), get_args(args[0])
    return annotation, origin, get_args(annotation)


def _deterministic_sentence(field_name: str, seed_text: str, rng: random.Random) -> str:
    templates = [
        "Deterministic mock summary for {field} derived from the supplied evidence.",
        "Mock-mode narration of {field}: evidence-grounded, no invented figures.",
        "{field} generated by the offline mock model from the frozen evidence context.",
    ]
    template = templates[rng.randrange(len(templates))]
    return template.format(field=field_name.replace("_", " "))


def _instance_for_model(schema: type[BaseModel], seed_name: str, seed_text: str, rng: random.Random) -> dict:
    result = {}
    for field_name, field in schema.model_fields.items():
        result[field_name] = _value_for_field(
            field_name, field.annotation, seed_text, rng, seed_name=f"{seed_name}.{field_name}"
        )
    return result


def _value_for_field(field_name: str, annotation, seed_text: str, rng: random.Random, seed_name: str | None = None):
    seed_name = seed_name or field_name
    # Extraction always uses the bare field name - evidence JSON keys match
    # output-model field names exactly regardless of nesting depth. seed_name
    # (which accumulates a path) is used only to vary generated filler text.
    extracted = _extract_from_text(seed_text, field_name)
    if extracted is not None:
        return extracted

    ann, origin, args = _unwrap_optional(annotation)

    if origin is list:
        item_ann = args[0] if args else str
        count = rng.randint(1, 3)
        return [
            _value_for_field(field_name, item_ann, seed_text, rng, seed_name=f"{seed_name}[{i}]")
            for i in range(count)
        ]

    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return _instance_for_model(ann, seed_name, seed_text, rng)
    if ann is str:
        return _deterministic_sentence(seed_name, seed_text, rng)
    if ann is float:
        return round(rng.uniform(1, 100), 2)
    if ann is int:
        return rng.randint(1, 100)
    if ann is bool:
        return rng.random() > 0.5
    return None


def deterministic_instance_dict(schema: type[BaseModel], seed_text: str) -> dict:
    rng = random.Random(_seed_from_text(seed_text))
    return _instance_for_model(schema, schema.__name__, seed_text, rng)


def deterministic_text(seed_text: str) -> str:
    rng = random.Random(_seed_from_text(seed_text))
    openers = [
        "Based on the grounded evidence provided",
        "Per the deterministic capacity and scoring data supplied",
        "Using only the evidence in context",
    ]
    return (
        f"{openers[rng.randrange(len(openers))]}, this is a deterministic mock-mode response. "
        f"No external model call was made; enable a real SAD_LLM__PROVIDER to get natural-language "
        f"narration in place of this placeholder sentence."
    )


class MockChatModel(BaseChatModel):
    """Deterministic, offline chat model. See module docstring."""

    response_schema: Optional[type[BaseModel]] = None

    model_config = {"arbitrary_types_allowed": True}

    @property
    def _llm_type(self) -> str:
        return "seekanddestroy-mock"

    def bind_response_schema(self, schema: type[BaseModel]) -> "MockChatModel":
        return MockChatModel(response_schema=schema)

    def _generate(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> ChatResult:
        prompt_text = "\n".join(
            m.content if isinstance(m.content, str) else json.dumps(m.content) for m in messages
        )
        schema = kwargs.get("response_schema") or self.response_schema
        if schema is not None:
            instance = deterministic_instance_dict(schema, prompt_text)
            text = json.dumps(instance, default=str)
        else:
            text = deterministic_text(prompt_text)
        message = AIMessage(content=text)
        return ChatResult(generations=[ChatGeneration(message=message)])


    async def _agenerate(
        self,
        messages: list[BaseMessage],
        stop: Optional[list[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> ChatResult:
        """Delegates. The mock does no I/O, so there is nothing to await - but
        the async path must still work end to end, and a BaseChatModel without
        _agenerate falls back to running _generate in a thread pool, which
        would quietly reintroduce the thread-per-call behaviour the async
        conversion exists to remove.
        """
        return self._generate(messages, stop=stop, **kwargs)
