<#
.SYNOPSIS
    Create and seed PraveenDB on a target SQL Server, and create the
    least-privilege application login.

.DESCRIPTION
    Used both for a fresh local install and for standing the database up on an
    Azure VM. There is deliberately no backup/restore step: the seed is
    deterministic (scripts/generate_seed.py, SEED=20240101), so running
    schema.sql + seed.sql reproduces the estate byte for byte - 96k rows from a
    6.6 MB script. That is faster than moving a .bak, and it means the database
    can be rebuilt from the repository at any time.

    What it does NOT copy: Investigation / InfrastructureRecommendation /
    RecommendationDecision history. Those are governance records generated by
    use. If you need them on the target, take a real backup instead.

    The application password is never taken as a parameter - it would land in
    shell history and in `ps` output. It is prompted for, or read from
    SAD_DB_PASSWORD.

.PARAMETER Server
    Target SQL Server. Local default instance, or <vm-ip>,1433 for Azure.

.PARAMETER AdminUser
    SQL admin login. Omit entirely to use Windows Integrated Security (local).

.EXAMPLE
    .\scripts\provision-database.ps1 -Server LAPTOP-R6U8H616

.EXAMPLE
    .\scripts\provision-database.ps1 -Server 20.51.x.x,1433 -AdminUser sqladmin
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Server,
    [string]$Database = "PraveenDB",
    [string]$AdminUser,
    [string]$AppLogin = "sad_app",
    [switch]$SkipSeed
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- how we authenticate to run the DDL ------------------------------------
if ($AdminUser) {
    $adminPassword = Read-Host -AsSecureString "SQL admin password for '$AdminUser'"
    $plainAdmin = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($adminPassword))
    $authArgs = @("-U", $AdminUser, "-P", $plainAdmin)
    Write-Host "auth: SQL login '$AdminUser'"
} else {
    $authArgs = @("-E")
    Write-Host "auth: Windows Integrated Security"
}

function Invoke-Sql {
    param([string[]]$ExtraArgs)
    # -b makes sqlcmd exit non-zero on error, so $ErrorActionPreference can
    # actually stop the script instead of it marching on through failures.
    & sqlcmd -S $Server @authArgs -C -b @ExtraArgs
    if ($LASTEXITCODE -ne 0) { throw "sqlcmd failed (exit $LASTEXITCODE)" }
}

Write-Host "`n=== 1. database ==="
Invoke-Sql @("-d", "master", "-Q",
    "IF DB_ID('$Database') IS NULL BEGIN CREATE DATABASE [$Database]; PRINT 'created $Database'; END ELSE PRINT '$Database already exists';")

Write-Host "`n=== 2. schema ==="
Invoke-Sql @("-d", $Database, "-i", (Join-Path $repoRoot "database\schema.sql"))

Write-Host "`n=== 3. migrations ==="
Get-ChildItem (Join-Path $repoRoot "database") -Filter "migration_*.sql" | Sort-Object Name | ForEach-Object {
    Write-Host "  $($_.Name)"
    Invoke-Sql @("-d", $Database, "-i", $_.FullName)
}

if (-not $SkipSeed) {
    Write-Host "`n=== 4. seed (96k rows - takes a minute) ==="
    Invoke-Sql @("-d", $Database, "-i", (Join-Path $repoRoot "database\seed.sql"))
} else {
    Write-Host "`n=== 4. seed SKIPPED ==="
}

Write-Host "`n=== 5. application login '$AppLogin' ==="
$appPassword = $env:SAD_DB_PASSWORD
if (-not $appPassword) {
    $secure = Read-Host -AsSecureString "Password for the '$AppLogin' SQL login"
    $appPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
}
if (-not $appPassword) { throw "no password supplied for $AppLogin" }

# Escaped for the T-SQL string literal below.
$escaped = $appPassword.Replace("'", "''")

# Least privilege on purpose: SELECT across the schema, INSERT/UPDATE on the
# five governance tables the platform actually writes, and nothing else. No
# sysadmin, no db_owner, no DDL - so the CMDB being read-only from every layer
# above SQL Server is enforced by the database, not by convention.
$grantScript = @"
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = '$AppLogin')
    CREATE LOGIN [$AppLogin] WITH PASSWORD = '$escaped', CHECK_POLICY = ON, DEFAULT_DATABASE = [$Database];
ELSE
    PRINT 'login $AppLogin already exists - password unchanged';
GO
USE [$Database];
GO
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = '$AppLogin')
    CREATE USER [$AppLogin] FOR LOGIN [$AppLogin];
GO
GRANT SELECT ON SCHEMA::sad TO [$AppLogin];
GRANT INSERT, UPDATE ON sad.Investigation                TO [$AppLogin];
GRANT INSERT, UPDATE ON sad.InfrastructureRecommendation TO [$AppLogin];
GRANT INSERT         ON sad.RecommendationDecision       TO [$AppLogin];
GRANT INSERT         ON sad.CapacityRequest              TO [$AppLogin];
GRANT INSERT         ON sad.AgentAuditLog                TO [$AppLogin];
GO
PRINT 'grants applied to $AppLogin';
GO
"@

$tempScript = Join-Path ([IO.Path]::GetTempPath()) "sad_grants_$([guid]::NewGuid().ToString('N')).sql"
try {
    Set-Content -Path $tempScript -Value $grantScript -Encoding utf8
    Invoke-Sql @("-d", "master", "-i", $tempScript)
} finally {
    # The script contains the password in plaintext - never leave it on disk.
    Remove-Item $tempScript -Force -ErrorAction SilentlyContinue
}

Write-Host "`n=== verification ==="
Invoke-Sql @("-d", $Database, "-h", "-1", "-W", "-Q",
    "SET NOCOUNT ON; SELECT 'tables=' + CAST(COUNT(*) AS VARCHAR) FROM sys.tables WHERE SCHEMA_NAME(schema_id)='sad'; SELECT 'clusters=' + CAST(COUNT(*) AS VARCHAR) FROM sad.InfrastructureCluster; SELECT 'nodes=' + CAST(COUNT(*) AS VARCHAR) FROM sad.ClusterNode;")

Write-Host "`nDone. Next:"
Write-Host "  1. set SAD_DB_USERNAME=$AppLogin and SAD_DB_PASSWORD in docker/.env"
Write-Host "  2. set a sign-in password:  python scripts\set_password.py E1001"
